lint:
  image: registry.gitlab.com/pipeline-components/ruff:latest
  before_script:
    - mkdir reports
  script:
    - ruff ./app

black:
  image:
    name: ${CI_REGISTRY}/common/base-images/flask:ubuntu-22.04
  before_script:
    - pip install -r requirements.txt
  script:
    - black -S --check --diff app

mypy-check:
  image:
    name: ${CI_REGISTRY}/common/base-images/flask:ubuntu-22.04
  before_script:
    - pip install -r requirements.txt
  script:
    - mypy app

build-image:
  image:
      name: gcr.io/kaniko-project/executor:debug
      entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  rules:
    # For default branch (main): tag image as "dev"
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      variables:
        TARGET_IMAGE_TAG: dev
    # For all other branches and git tags: use git branch/tag as image tag (e.g. "proxy:testing")
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
      variables:
        TARGET_IMAGE_TAG: $CI_COMMIT_REF_SLUG
  script:
    - >-
      /kaniko/executor
      --context $CI_PROJECT_DIR/
      --dockerfile $CI_PROJECT_DIR/Dockerfile.deployment
      --destination $CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_SHA
      --destination $CI_REGISTRY_IMAGE/proxy:$TARGET_IMAGE_TAG
      --cache-run-layers
      --cache-copy-layers
      --cache=true
