
HTTP_TO_HTTPS_HOSTS:
  - gbfs.nextbike.net
  - apis.deutschebahn.com
  - stables.donkey.bike
  - data.lime.bike
  - mds.bird.co
  - mds.bolt.eu
  - gbfs.prod.sharedmobility.ch
  - api.voiapp.io
  - gbfs.api.ridedott.com
  - zeus.city
  - yoio.rideatom.com
  - www.share-birrer.ch
