FROM python:3.11

WORKDIR /app

ENV PATH="${PATH}:/home/mitm/.local/bin/"
EXPOSE 8080

RUN adduser --system --disabled-login --home /home/mitm mitm && chown mitm /app
USER mitm

COPY addons.py ./addons.py

COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

COPY app ./app

CMD ["mitmdump", "-s", "addons.py"]
