FROM python:3.11

WORKDIR /app
EXPOSE 8080

ENV PATH="${PATH}:/home/mitm/.local/bin/"

RUN adduser --system --disabled-password --home /home/mitm mitm && chown mitm /app
USER mitm

COPY addons.py ./addons.py

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY app ./app

CMD ["mitmdump", "-s", "addons.py"]
