FROM python:3.11-alpine

WORKDIR /app

ENV PATH="${PATH}:/home/mitm/.local/bin/"
EXPOSE 8080

RUN apk add rust cargo

RUN adduser -S -D mitm && chown mitm /app
USER mitm

COPY addons.py ./addons.py

COPY requirements.txt .
RUN pip install -r requirements.txt

USER root
RUN apk del rust cargo
USER mitm

COPY app ./app

CMD ["mitmdump", "-s", "addons.py"]
